### ISSUE TITLE
How to customize Text tool or add TextStickerConfig

### ISSUE THREAD

**Issue by pnickv** [imgly/imgly-sdk-android-demo#35]
I tried to customize Text tool (to add a default text), but wasn't able to find a proper way to do that:
getCurrentTextStickerConfig() produces NPE.
I also tried to add a TextStickerConfig to stickers as a new sticker, but got  exception android.content.res.Resources$NotFoundException: Resource ID #0x0 (most likely because TextStickerConfig should extend AbstractConfig, so it looks like TextStickers are not supposed to be added to Stickers list).

Could you, pls, provide me with an example how to customize Text tool (to add default text), or|and how to add a custom TextSticker to Stickers list.

**Comment by svendvd** [comment]
Hi,

this is not part of the sdk. But you can implement it like this (Example for StickerCategories) https://github.com/imgly/imgly-sdk-android-demo/issues/28
Instead of ImageStickerConfig you must use an extended TextStickerConfig.

We can also create this customization for you. If you wish this, please contact our sales team.

Best,
Sven
